"""Initial migration

Revision ID: 93817b6a29a3
Revises: eea3b673bdef
Create Date: 2025-05-26 23:49:23.047882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93817b6a29a3'
down_revision = 'eea3b673bdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('kuiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_kuiz_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=200), nullable=False),
    sa.Column('options', sa.PickleType(), nullable=True),
    sa.Column('answer', sa.String(length=100), nullable=False),
    sa.Column('kuiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kuiz_id'], ['kuiz.id'], name='fk_question_kuiz_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_question_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kuiz_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kuiz_id'], ['kuiz.id'], name='fk_quizattempt_kuiz_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_quizattempt_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempt_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.String(length=100), nullable=True),
    sa.Column('correct_answer', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempt.id'], name='fk_attemptdetail_attempt_id'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='fk_attemptdetail_question_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_attempt_detail')
    op.drop_table('quiz_attempt')
    op.drop_table('question')
    op.drop_table('kuiz')
    op.drop_table('user')
    # ### end Alembic commands ###
