"""add visibility column to question

Revision ID: fe6e7632f253
Revises: 93817b6a29a3
Create Date: 2025-06-09 02:48:01.104110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6e7632f253'
down_revision = '93817b6a29a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('report_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('report_count')
        batch_op.drop_column('visibility')

    # ### end Alembic commands ###
